name: musicxml_domain
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  xml: ^6.0.0

dev_dependencies:
  custom_lint: ^0.8.0
  musicxml_lint:
    path: tools/musicxml_lint
  test: ^1.25.6
  very_good_analysis: ^7.0.0
